name: spike
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - astroid=2.14.2=py311h06a4308_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - click=8.0.4=py311h06a4308_0
  - colorama=0.4.6=py311h06a4308_0
  - dill=0.3.7=py311h06a4308_0
  - docstring-to-markdown=0.11=py311h06a4308_0
  - flake8=6.0.0=py311h06a4308_0
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.1=py311h06a4308_1
  - lazy-object-proxy=1.6.0=py311h5eee18b_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_2
  - packaging=23.1=py311h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pip=23.2.1=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - pluggy=1.0.0=py311h06a4308_1
  - pycodestyle=2.10.0=py311h06a4308_0
  - pydocstyle=6.3.0=py311h06a4308_0
  - pyflakes=3.0.1=py311h06a4308_0
  - pylint=2.16.2=py311h06a4308_0
  - python=3.11.4=h955ad1f_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.7.2=py311h06a4308_0
  - pytoolconfig=1.2.5=py311h06a4308_1
  - readline=8.2=h5eee18b_0
  - rope=1.7.0=py311h06a4308_0
  - setuptools=68.0.0=py311h06a4308_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomlkit=0.11.1=py311h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - ujson=5.4.0=py311h6a678d5_0
  - whatthepatch=1.0.2=py311h06a4308_0
  - wheel=0.38.4=py311h06a4308_0
  - wrapt=1.14.1=py311h5eee18b_0
  - xz=5.4.2=h5eee18b_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zlib=1.2.13=h5eee18b_0
